server:
  port: 8081

# Oracle #
spring:
  datasource:
    url: https://GFF656171692D4F-DBUAM2024.adb.sa-bogota-1.oraclecloudapps.com/ords/sql-developer
    username: ADMIN
    password: oracle
    driverClassName: oracle.jdbc.driver.OracleDriver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.Oracle12cDialect
    show-sql: true
    hibernate:
      ddl-auto: update